name: 测试

on:

  push:

    branches: [ master ]


jobs:

  master:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Project1

        uses: actions/checkout@v2

        with:
          repository: waifu-project/imgcomic_web

          ref: master
          path: xxx

      - name: Checkout Legado Project

        uses: actions/checkout@v2

        with:

          repository: waifu-project/imgcomic

          ref: master
        
      - name: Build Project
        working-directory: xxx
        run: |

          npm install

          npm run-script build

      - name: Upload Files

        uses: actions/upload-artifact@v2

        with:

          name: dist_master

          path: xxx/dist

          if-no-files-found: error
