name: ac

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TEST
        env:
          LANZOU_ID: ${{ secrets.LANZOU_ID }}
          LANZOU_PSD: ${{ secrets.LANZOU_PSD }}
        run: |
          echo '123'>>1.txt.apk
          bash ./.github/scripts/lzy.sh "1.txt.apk" "$GITHUB_WORKSPACE/1.txt.apk" "2219239" 

     
