name: 测试

on:
  watch:
    types: [started]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: python -V
      - name: python test
        run: |
          print 'hello the world'
          print('hello world.')
        shell: python
