name: 测试

on:
  watch:
    types: [started]
  push:
    branches: [master]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: python test
        run: print('hello world')
        shell: python
