name: Build YueDu 3

# https://docs.github.com/cn/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
# https://docs.github.com/cn/actions/reference/workflow-commands-for-github-actions
on:
 # schedule:
    # 美国时间每周六9时5分（中国时间每周六17时5分）
 #   - cron: '5 9 * * 6'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'Celeter' }}
    steps:
      # https://github.com/actions
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout this project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: actions

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up lanzou-api
        run: |
          pip install lanzou-api
#          python -V
#          python -m pip install --upgrade pip

      - name: Checkout android project
        uses: actions/checkout@v2
        with:
          repository: Celeter/YueDu3
          ref: master
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          path: legado

      - name: Remove 18PlusList.txt
        run: rm -f $GITHUB_WORKSPACE/legado/app/src/main/assets/18PlusList.txt

#       - name: App minify
#         run: |
#           sed '/minifyEnabled/i\            shrinkResources true' $GITHUB_WORKSPACE/legado/app/build.gradle -i
#           sed 's/minifyEnabled false/minifyEnabled true/'         $GITHUB_WORKSPACE/legado/app/build.gradle -i

      - name: Checkout private key
        uses: actions/checkout@v2
        with:
          repository: Celeter/secrets
          token: ${{ secrets.ACCESS_TOKEN }}
          path: key

      - name: Decrypt large secret
        run: bash $GITHUB_WORKSPACE/actions/.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.ANDROID_SECRET }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleGoogleRelease
        working-directory: legado

      - name: Update README.md
        run: |
          path="${{ github.workspace }}/legado/app/build/outputs/apk/google/release/"
          files=$(ls $path)
          for f in $files
          do
           if [[ $f == *"apk" ]]; then
            file=$f
           fi
          done
          // 获取文件名
          fileName="$(basename $file .apk)"
          // 获取文件路径
          filePath="${path}${file}"
          // 设置环境变量
          echo "APP_FILE=$file" >> $GITHUB_ENV
          echo "APP_NAME=$fileName" >> $GITHUB_ENV
          echo "APP_PATH=$filePath" >> $GITHUB_ENV
          // 更新README.md
          sed "3c ### 当前最新版本: $file" README.md -i
          sed "4c ### 最近更新时间: $(date -u -d '+8 hour' '+%Y-%m-%d %H:%M:%S')" README.md -i
          git config user.name  Robot
          git config user.email github-actions@github.com
          git commit -m "update README.md" -a
          git push
        working-directory: actions

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.APP_NAME }}
          release_name: ${{ env.APP_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APP_PATH }}
          asset_name: ${{ env.APP_FILE }}
          asset_content_type: application/vnd.android.package-archive

      - name: Upload App
        run: python ./actions/.github/scripts/API_lanzou.py
        env:
          LANZOU_ID: ${{ secrets.LANZOU_ID }}
          LANZOU_PSD: ${{ secrets.LANZOU_PSD }}
          LANZOU_FOLDER: '阅读3'
          UPLOAD_FOLDER: ${{ github.workspace }}/legado/app/build/outputs/apk/google/release/
