name: Build YueDu 3

# https://docs.github.com/cn/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows
on:
  schedule:
    # 美国时间每周六9时5分（中国时间每周六17时5分）
    - cron: '5 9 * * 6'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'Celeter' }}
    steps:
      # https://github.com/actions
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout this project
        uses: actions/checkout@v2
        with:
          path: actions

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up lanzou-api
        run: |
          pip install lanzou-api
#          python -V
#          python -m pip install --upgrade pip

      - name: Checkout android project
        uses: actions/checkout@v2
        with:
          repository: Celeter/YueDu3
          ref: master
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          path: legado

      - name: Remove 18PlusList.txt
        run: rm -f $GITHUB_WORKSPACE/legado/app/src/main/assets/18PlusList.txt

      - name: Checkout private key
        uses: actions/checkout@v2
        with:
          repository: Celeter/secrets
          token: ${{ secrets.ACCESS_TOKEN }}
          path: key

      - name: Decrypt large secret
        run: bash $GITHUB_WORKSPACE/actions/.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.ANDROID_SECRET }}

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleGoogleRelease
        working-directory: legado

      - name: Get current time
        uses: Celeter/current-time@v2.0.0
        id: current-time
        with:
          format: YY.MMDDHH
          utcOffset: "+08:00"

      - name: Rename App
        run: mv -f ${{ github.workspace }}/legado/app/build/outputs/apk/google/release/*.apk ${{ github.workspace }}/legado_google_3.${{ steps.current-time.outputs.formattedTime }}.apk

      - name: Upload App
        run: python ./actions/.github/scripts/API_lanzou.py
        env:
          LANZOU_ID: ${{ secrets.LANZOU_ID }}
          LANZOU_PSD: ${{ secrets.LANZOU_PSD }}
          FOLDER_NAME: '阅读3'
          FILE_PATH: ${{ github.workspace }}/legado_google_3.${{ steps.current-time.outputs.formattedTime }}.apk

      - name: Update README.md
        run: |
          sed "3c ### 当前最新版本: legado_google_3.${{ steps.current-time.outputs.formattedTime }}.apk" README.md -i
          sed "4c ### 最近更新时间: ${{ steps.current-time.outputs.readableTime }}" README.md -i
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git commit -m "update README.md" -a
          git push
        working-directory: actions

